name: Go CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1️⃣ Клонируем репозиторий
    - uses: actions/checkout@v4

    # 2️⃣ Устанавливаем Go
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.26.2'

    # 3️⃣ Загружаем зависимости проекта
    - name: Download dependencies
      run: go mod download

    # 4️⃣ Запуск golangci-lint через официальный Action
    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: v1.59.0

    # 5️⃣ Сборка проекта
    - name: Build
      run: go build ./...

    # 6️⃣ Запуск тестов
    - name: Test
      run: go test ./... -v -coverprofile=coverage.out